### PR TITLE
Vignette for basic natserv usage with a mapping tutorial 

### PR DESCRIPTION
**Pull request by mairindeith**
Pull request includes the knit vignette's .Rmd and associated files.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @mairindeith ! 

can you put the source files in `inst/vign/` instead?  then run the vignette to get the output and copy that to `vignettes/`

also, not sure what the main vignette source file is?  is it the .Rmd or the .tex?

**Comment by mairindeith** [comment]
Hi @sckott - sure! The .Rmd file is the source, and has been moved to `/inst/vign` with the final .Rmd in `vignettes/`. Please let me know if I goofed and this isn't what you were hoping for :smile: 

Did you want the knit .html file anywhere or should I remove it?

**Comment by sckott** [comment]
thanks @mairindeith - verry sorry for the delay. had a long vacation, then a cold. 

Looking good! 

I'd like to use the old style vignette without requiring `rmarkdown`, so change the header of the vignette to be 

```
<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Introduction to `natserve` - An R package to wrap NatureServe's database API from rOpenSci}
%\VignetteEncoding{UTF-8}
-->

## the knit options chunk

## the rest of the vignette ...
```

Thanks for putting the vignette in `inst/vign`.  What I meant to put in `vignettes` was the rendered output, not just a copy of the same file in `inst/vign`. So after switching the format above, just run the vignette (`knitr::knit('natserv_vignette.Rmd')`), then copy the `.md` output file of the same name to `vignettes` and change the extension to `.Rmd`

Please add two things to the DESCRPTION file: 

- `knitr` to Suggests
- add this entry somewhere: `VignetteBuilder: knitr`

**Comment by mairindeith** [comment]
Hi @sckott, thanks for the explicit instructions! The DESCRIPTION file already contained `knitr` under suggests and `VignetteBuilder: knitr` - seems like you set this up with [a previous commit](b50acec25255ddea3ac2fed4440b9eab2336c6cf).

Here's the current status of the vignette:

- updated header in `inst/vign/natserv_vignette.Rmd` to use `knitr` exclusively
- only the rendered output is in `vignettes`, copied as an `.Rmd` from the `.md` original

**Comment by sckott** [comment]
thanks @mairindeith ! just a few more things:

During R check I see:

```
* checking files in ‘vignettes’ ... NOTE
The following directory looks like a leftover from 'knitr':
  ‘figure’
Please remove from your package.
```

Please add `vignettes/figure` to the `.Rbuildignore` file so that R check doesn't complain. 

-------

the bit you have at the top of the vignette 

```
---
title: "Introduction to `natserve` - An R package to wrap NatureServe's database API from rOpenSci"
author: Vignette written by Mairin Deith for the package by Scott Chamberlain
output: 
   html_document:
     toc: true
     toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Introduction to `natserv`}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```

requires `rmarkdown` - Let's just add `rmarkdown` back in Suggests - though still only put the rendered vignette in `vignettes/` - 

Thanks!

**Comment by mairindeith** [comment]
Thanks for being such a patient teacher through this @sckott - I realised that my `knitr` command was knitting from the wrong input file. I re-knit the correct file and the `.Rmd` in `vignettes/` now has an rmarkdown-free header:

```
<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Introduction to `natserve` - An R package to wrap NatureServe's database API from rOpenSci}
%\VignetteEncoding{UTF-8}
-->

=====
```
We shouldn't have to add `rmarkdown` to Suggests now. Please let me know what other tweaks are necessary. Thanks!

**Comment by sckott** [comment]
looks good @mairindeith - thanks for all your work on this!

**Pull request merged**
