### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by DavidQuartey**

### CODE REVIEW

**Comment by sckott** [comment]
thanks @DavidQuartey !  Can you make those changes though in both `README.md` and `README.Rmd`

**Comment by DavidQuartey** [comment]
Hello @sckott, sorry for the delay in response. I'm new to this. I just realized its been closed. I do not know how to make the pull request with changes in 2 separate files. Its not clear after googling around.

**Comment by sckott** [comment]
👋  @DavidQuartey You can make the same change you made in the other file and then push the commit on the same branch `DavidQuartey:patch-1`  - If you can' figure it out, I can just merge this one! Let me know

**Comment by DavidQuartey** [comment]
Apologies, I just saw the notification due to it being closed. Please merge it if its still necessary, @sckott.

**Pull request closed without merging**
